-   repo: git@github.com:keybase/pre-commit.git
    sha: 'e56c58cc34b81fc814f10c5062c31c9db93376df'
    hooks:
    -   id: eslint
-   repo: git@github.com:keybase/pre-commit.git
    sha: 'e56c58cc34b81fc814f10c5062c31c9db93376df'
    hooks:
    -   id: flow
