install:

environment:
  global:
    GOPATH: c:\work\
    GO15VENDOREXPERIMENT: 1
    KEYBASE_SERVER_URI: https://ci1.keybase.io

# clone directory
clone_folder: c:\work\src\github.com\keybase\client

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
#platform: Any CPU

# scripts to run before build
before_build:

# scripts to run after build
# ...testing
# Note we do a ping, do save time if the test server is down.
# Most of the rest of this is to avoid running tests on vendored dirs.
after_build:
  - keybase ping
  - cd ..
  - go list ./... | find /V "vendor" > testlist.txt
  - for /f %%i in (testlist.txt) do go test -timeout 30m %%i

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cd go\keybase
  - go get
  - go build

# to disable automatic builds
#build: off
